### PR TITLE
Store config (RC, lowlatency) and Cron job for auto update

### PR DESCRIPTION
**Pull request by usbkey9**
Hi Chris,

Great job,
I just made some stuff to improve
Let me know if there is something you disagree

Best,

### CODE REVIEW

**Comment by MarauderXtreme** [comment]
Hi,

thank you for the contribution. I appreciate them.  
I will look further into this the next few days. But I have some suggestions right away.

1. Would you kindly rebase your branch and create some proper commits? At least write a meaningful summary for every commit. (Maybe this will make it easier to understand the changes) I don't want to squash your commits but I won't merge them like this.
2. If you can, could you sign the commits? I don't require this, but it would be nice. ^^
3. I've seen that you added some cron functionality. I don't think that a kernel update should be something that is done by a cronjob since things can go horribly wrong. You could keep this but add a warning to it!

I will look into the other changes and give feedback soon.

--
Chris

**Comment by usbkey9** [comment]
Hi,

I add a cron job but before, the setup ask to the user.
And this can be undo by running the script a second time and say that you
don't want to make a cronjob

**Comment by MarauderXtreme** [comment]
I'll close this one in favor of #2 .

**Comment by usbkey9** [comment]
Thanks, I didn't see any option to do it by myself

**Pull request closed without merging**
