### PR TITLE
Split ukupgrade for storing kernel config (rc, lowlatency) and add cool stuff

### PR DESCRIPTION
**Pull request by usbkey9**
Sorry for signing commit but I had never practiced that and I don't think I'll so

### CODE REVIEW

**Comment by MarauderXtreme** [comment]
No Problem with the signing of commits. As I said, I wouldn't require it. It's just a nice to have.

First of all. Let me thank you for your work. I myself tried to work on a same version check and creating some kind of non-interactive mode for this script.

I see this script as some kind of drop-in solution for different environments. Maybe some of them don't have git installed or people don't want to set it up first. 

1. Could you change the logic of the setup script to only call the `ukupgrade script and run it in a setup environment. (Maybe set a variable that makes the script save the config in the end)  
  1.1. Let the ukupgrade script skip the interactive mode if it can find the config file
  1.2. If you want a challenge you could extend the script that it asks only for parameters that aren't set. (Maybe helpful if someone wants to switch from rc to stable or vice versa)
2. Rename `uk.cfg` to `uku.cfg` to clarify that it is a config file for the `ukupgrade` script. (I don't see config option for `ukpurge` but better safe than sorry. ^^)
3. Add a `sample.uk.cfg` that people know what can be configured and want to do it manually.
4. Please emphasize that the cron job should only be configured, if the user knows what it implies and what needs to be taken care of. (Occasional restart with the knowledge of a changed kernel and whatever)
5. Put the config file under something like `/etc/uktools/uku.cfg`. I don't think it's a good idea to put this into the cron directories.
6. Could you include your setup possibility into the `Makefile`?

Thank you in advance.

**Comment by usbkey9** [comment]
Hi Chris,

Thank for congrats,

Even if git is not installed by default on all system, if people are on
github, I think they have git (or at least they should).
There is the zip option too.

1) I don't understand wath you are looking for
1.1) I made the system to work like that : if config are not set, ukupgrade
exec will run setup first. So why skip the interactive mode ??
1.2) Please Chris, there is only 4 params, I hope people will not be as
lazy as that
2) Done
3) Done
4) I don't understand, can you explain
5) Done, I remade cron system so
6) Done

I commited changes, so I wait your returns to finish work and after we'll
merge, ok ?

**Comment by usbkey9** [comment]
I can ask to the user, at when (hours) he want the script be executed

**Comment by usbkey9** [comment]
Hi Chris,

I update the setup script to run cronjob every 5 hours, so no more problem
with desktops updates.

Best,

**Comment by MarauderXtreme** [comment]
Hi,

sorry for not replying faster but I was busy with other things.

I still think it would be better if the option to curl the script directly would be still available. As I said I want this script to be as useful as possible and running the sccript without having to set it up first is better for certain environments.  
What I meant with number one is related to my prior point. I want the setup to be optional and not necessarry. I want that the `setup` calls the `ukupgrade` script and saves the config afterwards. (Maybe by passing a variable to the `ukupgrade` script, that it makes it to store the variables) That should also explain 1.1.

Number four is regarding the possible faults when setting up a cronjob for upgrade. (I have a server environment in mind here). If a machine is not rebooted after running the upgrade and more new kernel get installed it could happen that the newer kernel results in bootproblems and so on. I want a warning prior to the installation that it should only be done if people know what they do.

**Comment by usbkey9** [comment]
Hi,

Sorry but I don't understand you well ...
If people are on the github project, is that :

- they know how to clone repo, or at least download and extract zip file
(which is not optimized for keeping repo up-to-date)
- sorry but can you give me an user case for explanation because I really
don't understand what is wrong/unoptimized with my actual code
- they want the last kernel (get it is at they own risks btw), even on
server side (maybe I can leave a message on "Message of the Day" like
standard kernel update)

Best,

**Comment by usbkey9** [comment]
There is actually a bug with makefile, I push asap

**Comment by usbkey9** [comment]
I pushed last bug

**Comment by MarauderXtreme** [comment]
Hi there,

I told you what I want this project to be. It should be possible to use this script as temporary, drop-in solution. So cloning or downloading a zip is to much in my opinion. I have a CI or any other test situation in mind, where the latest kernel is needed to test once or twice. So always having to set it up in first place doesn't help. That is why I want this one to be a script on it's own with an option to set it up.

**Comment by usbkey9** [comment]
Ok, so if I implement command line option with settings (rc, lowlatency
etc) when running ukupgrade, it's okay for you ?

**Comment by usbkey9** [comment]
Plus one line command to download, extract and run the script

**Comment by usbkey9** [comment]
When I say " command line option with settings" I mean arguments

**Comment by usbkey9** [comment]
I pushed last version,
Check it out

**Comment by usbkey9** [comment]
You'll have to merge for one-line install works well

**Comment by MarauderXtreme** [comment]
I will have a look at your current version next week.

**Comment by MarauderXtreme** [comment]
I'll merge this for now. It looks good so far but I need to double check some of the more specific changes.

**Comment by usbkey9** [comment]
Regards to all code that I've updated, I think that it'll be better for
everyone, that I stay maintainer of project.
Thanks for your feedback.
Can you redirect your version to mine please

**Pull request merged**
